- name: "OPEN TO EVERYONE"
  icon: "users"
  description: "Hacktoberfest is open to everyone in our global community. Whether you’re a developer, or a student learner you can help drive growth of open source and make positive contributions to an ever-growing community."

- name: "NO HARDCORE REQUIREMENTS"
  icon: "check"
  description: "All backgrounds and skill levels are encouraged to complete the challenge."

- name: "MONTH LONG CHALLENGE"
  icon: "calendar"
  description: "You can sign in anytime between October 1 to October 31, 2020 to participate and complete the challenge."
